
# STRATEGIC PRICING ANALYSIS

In [28]:
import pandas as pd
import numpy as np

In [29]:
product_elasticity=pd.read_csv("product_elasticity.csv")

In [18]:
# ============================================================
# STEP 1 — ELASTICITY SUMMARY
# ============================================================

elasticity_summary = (
    product_elasticity
    .groupby("Elasticity_Type")
    .agg(
        Products=("Stock_Code", "nunique"),
        Total_Revenue=("Total_Revenue", "sum"),
        Total_Quantity=("Total_Quantity", "sum")
    )
    .reset_index()
)

display(elasticity_summary)

      Elasticity_Type  Products  Total_Revenue  Total_Quantity
0             Elastic      1296     1612423.47          948306
1           Inelastic       615     1143472.50          569522
2  Positive / Unusual      1371     1795322.52          988927

In [19]:
# ============================================================
# HIGH-REVENUE ELASTIC PRODUCTS
# ============================================================

high_revenue_elastic = product_elasticity[
    product_elasticity["Elasticity_Type"] == "Elastic"
].copy()

high_revenue_elastic = high_revenue_elastic.sort_values(
    "Total_Revenue",
    ascending=False
)

display(
    high_revenue_elastic[
        [
            "Stock_Code",
            "Average_Elasticity",
            "Average_Price",
            "Total_Quantity",
            "Total_Revenue",
            "Number_of_Months",
            "Elasticity_Type"
        ]
    ].head(20)
)

,Stock_Code,Average_Elasticity,Average_Price,Total_Quantity,Total_Revenue,Number_of_Months,Elasticity_Type
894,85099B,-1.077826,2.232254,22749,40752.62,7,Elastic
2532,22423,-3.184956,14.607622,2505,30675.89,2,Elastic
406,47566,-2.464349,5.908978,5946,29499.25,8,Elastic
1090,20685,-2.576660,8.148875,2481,17614.00,6,Elastic
400,21754,-2.820667,6.630387,2782,16990.70,8,Elastic
827,22469,-2.055437,1.926008,9594,16549.12,7,Elastic
557,22383,-1.319090,2.014618,9347,15632.93,8,Elastic
1203,21232,-3.862724,1.508068,10865,13899.62,6,Elastic
1035,21928,-2.905887,2.323260,7398,13794.46,6,Elastic
275,84946,-3.585780,1.569496,10219,13627.77,9,Elastic
1024,21731,-4.183084,2.085372,7921,13080.99,6,Elastic
1416,48138,-3.614964,7.864391,1939,12821.05,5,Elastic
87,21977,-1.439739,0.696603,24885,12551.67,10,Elastic
1716,22470,-1.299261,3.266839,3892,12117.68,4,Elastic
481,82486,-3.271016,8.188911,1530,11635.63,8,Elastic
29,21210,-1.076417,1.772094,8002,11494.40,11,Elastic
1435,21733,-3.534384,3.074216,3979,11108.24,5,Elastic
86,84970S,-1.116206,1.078679,13751,11057.05,10,Elastic
208,84836,-1.426695,1.404432,8895,10871.25,9,Elastic
1576,15056BL,-5.568435,6.188939,2224,10663.71,5,Elastic

In [20]:
# ============================================================
# HIGH-REVENUE INELASTIC PRODUCTS
# ============================================================

high_revenue_inelastic = product_elasticity[
    product_elasticity["Elasticity_Type"] == "Inelastic"
].copy()

high_revenue_inelastic = high_revenue_inelastic.sort_values(
    "Total_Revenue",
    ascending=False
)

display(
    high_revenue_inelastic[
        [
            "Stock_Code",
            "Average_Elasticity",
            "Average_Price",
            "Total_Quantity",
            "Total_Revenue",
            "Number_of_Months",
            "Elasticity_Type"
        ]
    ].head(20)
)

,Stock_Code,Average_Elasticity,Average_Price,Total_Quantity,Total_Revenue,Number_of_Months,Elasticity_Type
10,M,-0.243670,436.843403,2623,207975.16,11,Inelastic
1,POST,-0.317668,26.362858,2185,46552.59,12,Inelastic
225,21929,-0.973992,2.336468,10996,20088.46,9,Inelastic
1250,21843,-0.182841,11.558097,1791,18657.63,6,Inelastic
1535,84879,-0.889354,2.260968,11268,18641.32,5,Inelastic
747,20914,-0.940293,3.190787,6593,18317.59,7,Inelastic
748,48194,-0.828854,8.350106,2147,14098.27,7,Inelastic
49,84406B,-0.086177,3.393945,4692,14086.78,11,Inelastic
556,22326,-0.280201,3.335724,4585,13411.79,8,Inelastic
1047,21915,-0.523203,1.383983,11724,13210.52,6,Inelastic
936,22379,-0.404475,2.735529,5918,12981.31,7,Inelastic
1355,85099C,-0.504527,2.258138,6320,12009.09,5,Inelastic
1541,22622,-0.928642,11.325477,1193,11607.84,5,Inelastic
710,84078A,-0.879863,51.822714,286,11543.50,7,Inelastic
63,21213,-0.435526,0.704369,20930,11046.02,10,Inelastic
835,22492,-0.418683,0.764416,16256,10389.93,7,Inelastic
922,22382,-0.514486,1.824709,6156,10182.76,7,Inelastic
67,35004C,-0.513953,7.655712,1956,10137.64,10,Inelastic
807,71477,-0.653387,3.765853,3437,9991.63,7,Inelastic
44,21535,-0.248571,2.834065,3775,9461.08,11,Inelastic

In [21]:
# ============================================================
# PRICING OPPORTUNITY MATRIX
# ============================================================

product_elasticity["Pricing_Strategy"] = np.where(
    product_elasticity["Elasticity_Type"] == "Elastic",
    "Protect Price / Targeted Discount",
    np.where(
        product_elasticity["Elasticity_Type"] == "Inelastic",
        "Test Moderate Price Increase",
        "Review Further"
    )
)

display(
    product_elasticity[
        [
            "Stock_Code",
            "Average_Elasticity",
            "Average_Price",
            "Total_Quantity",
            "Total_Revenue",
            "Number_of_Months",
            "Elasticity_Type",
            "Pricing_Strategy"
        ]
    ].head(20)
)

,Stock_Code,Average_Elasticity,Average_Price,Total_Quantity,Total_Revenue,Number_of_Months,Elasticity_Type,Pricing_Strategy
0,DOT,0.216521,172.396849,681,97834.13,12,Positive / Unusual,Review Further
1,POST,-0.317668,26.362858,2185,46552.59,12,Inelastic,Test Moderate Price Increase
2,85216,-0.187747,1.961057,2559,1873.03,12,Inelastic,Test Moderate Price Increase
3,21533,-0.296496,5.445326,1870,9296.93,12,Inelastic,Test Moderate Price Increase
4,21657,-0.743393,8.668368,223,1715.81,12,Inelastic,Test Moderate Price Increase
5,40016,-0.482552,1.728526,9866,3337.10,12,Inelastic,Test Moderate Price Increase
6,21700,-1.625100,2.777797,4020,4113.12,12,Elastic,Protect Price / Targeted Discount
7,37370,-0.576954,5.535967,4551,7057.41,12,Inelastic,Test Moderate Price Increase
8,20724,0.226913,1.072685,13893,13051.79,12,Positive / Unusual,Review Further
9,21983,-0.643135,0.380495,3778,1087.84,12,Inelastic,Test Moderate Price Increase
10,M,-0.243670,436.843403,2623,207975.16,11,Inelastic,Test Moderate Price Increase
11,21215,-0.525010,0.848371,2859,1613.24,11,Inelastic,Test Moderate Price Increase
12,22080,1.126409,1.927389,2322,3919.96,11,Positive / Unusual,Review Further
13,21975,-0.686215,0.640983,16207,7823.26,11,Inelastic,Test Moderate Price Increase
14,20716,-1.653430,1.523833,930,1196.46,11,Elastic,Protect Price / Targeted Discount
15,71279,-0.049014,4.035333,97,342.39,11,Inelastic,Test Moderate Price Increase
16,21411,0.257068,4.890235,1074,4498.60,11,Positive / Unusual,Review Further
17,20671,-0.848920,1.517873,746,975.52,11,Inelastic,Test Moderate Price Increase
18,20674,-1.325676,1.459146,1542,1966.66,11,Elastic,Protect Price / Targeted Discount
19,21976,-2.903840,0.731048,8181,4327.50,11,Elastic,Protect Price / Targeted Discount

In [22]:
# ============================================================
# DAY 6 — STEP 5
# TOP PRICING OPPORTUNITIES
# ============================================================

reliable_products = product_elasticity[
    product_elasticity["Number_of_Months"] >= 4
].copy()

print(f"Reliable products: {len(reliable_products):,}")

display(
    reliable_products[
        [
            "Stock_Code",
            "Average_Elasticity",
            "Average_Price",
            "Total_Quantity",
            "Total_Revenue",
            "Number_of_Months",
            "Elasticity_Type",
            "Pricing_Strategy"
        ]
    ]
    .sort_values("Total_Revenue", ascending=False)
    .head(20)
)

Reliable products: 1,904

,Stock_Code,Average_Elasticity,Average_Price,Total_Quantity,Total_Revenue,Number_of_Months,Elasticity_Type,Pricing_Strategy
10,M,-0.243670,436.843403,2623,207975.16,11,Inelastic,Test Moderate Price Increase
0,DOT,0.216521,172.396849,681,97834.13,12,Positive / Unusual,Review Further
1869,85123A,0.213845,3.020471,17335,46817.52,4,Positive / Unusual,Review Further
1,POST,-0.317668,26.362858,2185,46552.59,12,Inelastic,Test Moderate Price Increase
894,85099B,-1.077826,2.232254,22749,40752.62,7,Elastic,Protect Price / Targeted Discount
406,47566,-2.464349,5.908978,5946,29499.25,8,Elastic,Protect Price / Targeted Discount
421,85099F,4.091470,2.227201,13135,23980.60,8,Positive / Unusual,Review Further
574,20725,2.568798,2.075503,13470,22998.81,8,Positive / Unusual,Review Further
328,21212,0.390219,0.672564,41557,22030.43,9,Positive / Unusual,Review Further
227,21931,0.388710,2.327740,10727,20630.64,9,Positive / Unusual,Review Further
225,21929,-0.973992,2.336468,10996,20088.46,9,Inelastic,Test Moderate Price Increase
892,22386,1.330932,2.289884,10774,20007.90,7,Positive / Unusual,Review Further
1250,21843,-0.182841,11.558097,1791,18657.63,6,Inelastic,Test Moderate Price Increase
1535,84879,-0.889354,2.260968,11268,18641.32,5,Inelastic,Test Moderate Price Increase
184,21137,1.912729,4.047289,5393,18621.21,9,Positive / Unusual,Review Further
747,20914,-0.940293,3.190787,6593,18317.59,7,Inelastic,Test Moderate Price Increase
1090,20685,-2.576660,8.148875,2481,17614.00,6,Elastic,Protect Price / Targeted Discount
506,82494L,0.337704,3.161564,6101,17257.36,8,Positive / Unusual,Review Further
400,21754,-2.820667,6.630387,2782,16990.70,8,Elastic,Protect Price / Targeted Discount
1499,21623,1.545307,10.297065,2341,16974.22,5,Positive / Unusual,Review Further

In [23]:
# ============================================================
# DAY 6 — STEP 6
# HIGH-VALUE PRICING SEGMENTS
# ============================================================

# Find the median revenue among reliable products
revenue_threshold = reliable_products["Total_Revenue"].median()

print(f"Revenue threshold: £{revenue_threshold:,.2f}")

# Create revenue segment
reliable_products["Revenue_Segment"] = np.where(
    reliable_products["Total_Revenue"] >= revenue_threshold,
    "High Revenue",
    "Lower Revenue"
)

# Display the important combinations
pricing_opportunities = (
    reliable_products[
        reliable_products["Revenue_Segment"] == "High Revenue"
    ]
    .sort_values("Total_Revenue", ascending=False)
)

display(
    pricing_opportunities[
        [
            "Stock_Code",
            "Average_Elasticity",
            "Average_Price",
            "Total_Quantity",
            "Total_Revenue",
            "Number_of_Months",
            "Elasticity_Type",
            "Revenue_Segment",
            "Pricing_Strategy"
        ]
    ].head(20)
)

Revenue threshold: £672.52

,Stock_Code,Average_Elasticity,Average_Price,Total_Quantity,Total_Revenue,Number_of_Months,Elasticity_Type,Revenue_Segment,Pricing_Strategy
10,M,-0.243670,436.843403,2623,207975.16,11,Inelastic,High Revenue,Test Moderate Price Increase
0,DOT,0.216521,172.396849,681,97834.13,12,Positive / Unusual,High Revenue,Review Further
1869,85123A,0.213845,3.020471,17335,46817.52,4,Positive / Unusual,High Revenue,Review Further
1,POST,-0.317668,26.362858,2185,46552.59,12,Inelastic,High Revenue,Test Moderate Price Increase
894,85099B,-1.077826,2.232254,22749,40752.62,7,Elastic,High Revenue,Protect Price / Targeted Discount
406,47566,-2.464349,5.908978,5946,29499.25,8,Elastic,High Revenue,Protect Price / Targeted Discount
421,85099F,4.091470,2.227201,13135,23980.60,8,Positive / Unusual,High Revenue,Review Further
574,20725,2.568798,2.075503,13470,22998.81,8,Positive / Unusual,High Revenue,Review Further
328,21212,0.390219,0.672564,41557,22030.43,9,Positive / Unusual,High Revenue,Review Further
227,21931,0.388710,2.327740,10727,20630.64,9,Positive / Unusual,High Revenue,Review Further
225,21929,-0.973992,2.336468,10996,20088.46,9,Inelastic,High Revenue,Test Moderate Price Increase
892,22386,1.330932,2.289884,10774,20007.90,7,Positive / Unusual,High Revenue,Review Further
1250,21843,-0.182841,11.558097,1791,18657.63,6,Inelastic,High Revenue,Test Moderate Price Increase
1535,84879,-0.889354,2.260968,11268,18641.32,5,Inelastic,High Revenue,Test Moderate Price Increase
184,21137,1.912729,4.047289,5393,18621.21,9,Positive / Unusual,High Revenue,Review Further
747,20914,-0.940293,3.190787,6593,18317.59,7,Inelastic,High Revenue,Test Moderate Price Increase
1090,20685,-2.576660,8.148875,2481,17614.00,6,Elastic,High Revenue,Protect Price / Targeted Discount
506,82494L,0.337704,3.161564,6101,17257.36,8,Positive / Unusual,High Revenue,Review Further
400,21754,-2.820667,6.630387,2782,16990.70,8,Elastic,High Revenue,Protect Price / Targeted Discount
1499,21623,1.545307,10.297065,2341,16974.22,5,Positive / Unusual,High Revenue,Review Further

In [24]:
# ============================================================
# DAY 6 — STEP 7
# FINAL PRICING OPPORTUNITY TABLE
# ============================================================

final_pricing_opportunities = pricing_opportunities[
    pricing_opportunities["Elasticity_Type"].isin(
        ["Elastic", "Inelastic"]
    )
].copy()

# Create business priority
final_pricing_opportunities["Priority"] = np.where(
    final_pricing_opportunities["Elasticity_Type"] == "Inelastic",
    "High",
    "Medium"
)

# Sort by priority and revenue
final_pricing_opportunities = (
    final_pricing_opportunities
    .sort_values(
        ["Priority", "Total_Revenue"],
        ascending=[True, False]
    )
)

display(
    final_pricing_opportunities[
        [
            "Stock_Code",
            "Average_Elasticity",
            "Average_Price",
            "Total_Quantity",
            "Total_Revenue",
            "Number_of_Months",
            "Elasticity_Type",
            "Pricing_Strategy",
            "Priority"
        ]
    ].head(20)
)

,Stock_Code,Average_Elasticity,Average_Price,Total_Quantity,Total_Revenue,Number_of_Months,Elasticity_Type,Pricing_Strategy,Priority
10,M,-0.243670,436.843403,2623,207975.16,11,Inelastic,Test Moderate Price Increase,High
1,POST,-0.317668,26.362858,2185,46552.59,12,Inelastic,Test Moderate Price Increase,High
225,21929,-0.973992,2.336468,10996,20088.46,9,Inelastic,Test Moderate Price Increase,High
1250,21843,-0.182841,11.558097,1791,18657.63,6,Inelastic,Test Moderate Price Increase,High
1535,84879,-0.889354,2.260968,11268,18641.32,5,Inelastic,Test Moderate Price Increase,High
747,20914,-0.940293,3.190787,6593,18317.59,7,Inelastic,Test Moderate Price Increase,High
748,48194,-0.828854,8.350106,2147,14098.27,7,Inelastic,Test Moderate Price Increase,High
49,84406B,-0.086177,3.393945,4692,14086.78,11,Inelastic,Test Moderate Price Increase,High
556,22326,-0.280201,3.335724,4585,13411.79,8,Inelastic,Test Moderate Price Increase,High
1047,21915,-0.523203,1.383983,11724,13210.52,6,Inelastic,Test Moderate Price Increase,High
936,22379,-0.404475,2.735529,5918,12981.31,7,Inelastic,Test Moderate Price Increase,High
1355,85099C,-0.504527,2.258138,6320,12009.09,5,Inelastic,Test Moderate Price Increase,High
1541,22622,-0.928642,11.325477,1193,11607.84,5,Inelastic,Test Moderate Price Increase,High
710,84078A,-0.879863,51.822714,286,11543.50,7,Inelastic,Test Moderate Price Increase,High
63,21213,-0.435526,0.704369,20930,11046.02,10,Inelastic,Test Moderate Price Increase,High
835,22492,-0.418683,0.764416,16256,10389.93,7,Inelastic,Test Moderate Price Increase,High
922,22382,-0.514486,1.824709,6156,10182.76,7,Inelastic,Test Moderate Price Increase,High
67,35004C,-0.513953,7.655712,1956,10137.64,10,Inelastic,Test Moderate Price Increase,High
807,71477,-0.653387,3.765853,3437,9991.63,7,Inelastic,Test Moderate Price Increase,High
44,21535,-0.248571,2.834065,3775,9461.08,11,Inelastic,Test Moderate Price Increase,High

In [25]:
# Check high-revenue elastic products
high_revenue_elastic = pricing_opportunities[
    pricing_opportunities["Elasticity_Type"] == "Elastic"
].copy()

display(
    high_revenue_elastic[
        [
            "Stock_Code",
            "Average_Elasticity",
            "Average_Price",
            "Total_Quantity",
            "Total_Revenue",
            "Number_of_Months",
            "Elasticity_Type",
            "Pricing_Strategy"
        ]
    ]
    .sort_values("Total_Revenue", ascending=False)
    .head(20)
)

,Stock_Code,Average_Elasticity,Average_Price,Total_Quantity,Total_Revenue,Number_of_Months,Elasticity_Type,Pricing_Strategy
894,85099B,-1.077826,2.232254,22749,40752.62,7,Elastic,Protect Price / Targeted Discount
406,47566,-2.464349,5.908978,5946,29499.25,8,Elastic,Protect Price / Targeted Discount
1090,20685,-2.576660,8.148875,2481,17614.00,6,Elastic,Protect Price / Targeted Discount
400,21754,-2.820667,6.630387,2782,16990.70,8,Elastic,Protect Price / Targeted Discount
827,22469,-2.055437,1.926008,9594,16549.12,7,Elastic,Protect Price / Targeted Discount
557,22383,-1.319090,2.014618,9347,15632.93,8,Elastic,Protect Price / Targeted Discount
1203,21232,-3.862724,1.508068,10865,13899.62,6,Elastic,Protect Price / Targeted Discount
1035,21928,-2.905887,2.323260,7398,13794.46,6,Elastic,Protect Price / Targeted Discount
275,84946,-3.585780,1.569496,10219,13627.77,9,Elastic,Protect Price / Targeted Discount
1024,21731,-4.183084,2.085372,7921,13080.99,6,Elastic,Protect Price / Targeted Discount
1416,48138,-3.614964,7.864391,1939,12821.05,5,Elastic,Protect Price / Targeted Discount
87,21977,-1.439739,0.696603,24885,12551.67,10,Elastic,Protect Price / Targeted Discount
1716,22470,-1.299261,3.266839,3892,12117.68,4,Elastic,Protect Price / Targeted Discount
481,82486,-3.271016,8.188911,1530,11635.63,8,Elastic,Protect Price / Targeted Discount
29,21210,-1.076417,1.772094,8002,11494.40,11,Elastic,Protect Price / Targeted Discount
1435,21733,-3.534384,3.074216,3979,11108.24,5,Elastic,Protect Price / Targeted Discount
86,84970S,-1.116206,1.078679,13751,11057.05,10,Elastic,Protect Price / Targeted Discount
208,84836,-1.426695,1.404432,8895,10871.25,9,Elastic,Protect Price / Targeted Discount
1576,15056BL,-5.568435,6.188939,2224,10663.71,5,Elastic,Protect Price / Targeted Discount
1305,22139,-2.510777,5.952932,2074,10643.31,5,Elastic,Protect Price / Targeted Discount

In [26]:
# Add Pricing Strategy

product_elasticity["Pricing_Strategy"] = np.where(
    product_elasticity["Elasticity_Type"] == "Elastic",
    "Protect Price / Targeted Discount",
    np.where(
        product_elasticity["Elasticity_Type"] == "Inelastic",
        "Test Moderate Price Increase",
        "Review Further"
    )
)

# Update the existing CSV file
product_elasticity.to_csv(
    "product_elasticity.csv",
    index=False
)

print("product_elasticity.csv updated successfully! ✅")

product_elasticity.csv updated successfully! ✅

In [27]:
# ============================================================
# FINAL PRICING OPPORTUNITIES
# ============================================================

reliable_products = product_elasticity[
    product_elasticity["Number_of_Months"] >= 4
].copy()

reliable_products["Priority"] = np.where(
    (
        (reliable_products["Elasticity_Type"] == "Elastic") &
        (reliable_products["Total_Revenue"] >= reliable_products["Total_Revenue"].median())
    ),
    "High",
    np.where(
        reliable_products["Elasticity_Type"] == "Inelastic",
        "Medium",
        "Review"
    )
)

pricing_opportunities = reliable_products[
    [
        "Stock_Code",
        "Average_Elasticity",
        "Average_Price",
        "Total_Quantity",
        "Total_Revenue",
        "Number_of_Months",
        "Elasticity_Type",
        "Pricing_Strategy",
        "Priority"
    ]
].sort_values(
    "Total_Revenue",
    ascending=False
)

display(pricing_opportunities.head(20))

pricing_opportunities.to_csv(
    "final_pricing_opportunities.csv",
    index=False
)

print("final_pricing_opportunities.csv saved successfully!")

,Stock_Code,Average_Elasticity,Average_Price,Total_Quantity,Total_Revenue,Number_of_Months,Elasticity_Type,Pricing_Strategy,Priority
10,M,-0.243670,436.843403,2623,207975.16,11,Inelastic,Test Moderate Price Increase,Medium
0,DOT,0.216521,172.396849,681,97834.13,12,Positive / Unusual,Review Further,Review
1869,85123A,0.213845,3.020471,17335,46817.52,4,Positive / Unusual,Review Further,Review
1,POST,-0.317668,26.362858,2185,46552.59,12,Inelastic,Test Moderate Price Increase,Medium
894,85099B,-1.077826,2.232254,22749,40752.62,7,Elastic,Protect Price / Targeted Discount,High
406,47566,-2.464349,5.908978,5946,29499.25,8,Elastic,Protect Price / Targeted Discount,High
421,85099F,4.091470,2.227201,13135,23980.60,8,Positive / Unusual,Review Further,Review
574,20725,2.568798,2.075503,13470,22998.81,8,Positive / Unusual,Review Further,Review
328,21212,0.390219,0.672564,41557,22030.43,9,Positive / Unusual,Review Further,Review
227,21931,0.388710,2.327740,10727,20630.64,9,Positive / Unusual,Review Further,Review
225,21929,-0.973992,2.336468,10996,20088.46,9,Inelastic,Test Moderate Price Increase,Medium
892,22386,1.330932,2.289884,10774,20007.90,7,Positive / Unusual,Review Further,Review
1250,21843,-0.182841,11.558097,1791,18657.63,6,Inelastic,Test Moderate Price Increase,Medium
1535,84879,-0.889354,2.260968,11268,18641.32,5,Inelastic,Test Moderate Price Increase,Medium
184,21137,1.912729,4.047289,5393,18621.21,9,Positive / Unusual,Review Further,Review
747,20914,-0.940293,3.190787,6593,18317.59,7,Inelastic,Test Moderate Price Increase,Medium
1090,20685,-2.576660,8.148875,2481,17614.00,6,Elastic,Protect Price / Targeted Discount,High
506,82494L,0.337704,3.161564,6101,17257.36,8,Positive / Unusual,Review Further,Review
400,21754,-2.820667,6.630387,2782,16990.70,8,Elastic,Protect Price / Targeted Discount,High
1499,21623,1.545307,10.297065,2341,16974.22,5,Positive / Unusual,Review Further,Review

final_pricing_opportunities.csv saved successfully!